// Server functions for the monthly salary / employment-package model.
//
// Concepts
// - employment_packages: per-employee active job + monthly salary + perks
// - salary_disbursements: one row per (user, year, month) generated by cron
// - incentive_pocket: overtime credits (rupee amount) accrued from the 8h cap
//   trigger, plus admin-issued bonuses
//
// All admin-facing functions go through `assertAdmin()`.

import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { sendEmailViaResend } from "@/server/email";

async function assertAdmin(userId: string) {
  const { data, error } = await supabaseAdmin
    .from("user_roles")
    .select("role")
    .eq("user_id", userId)
    .eq("role", "admin")
    .maybeSingle();
  if (error) throw new Error(error.message);
  if (!data) throw new Error("Forbidden: admin role required");
}

function siteUrl(): string {
  return (process.env.PUBLIC_SITE_URL || "https://amzsolution.site").replace(/\/$/, "");
}

function emailShell(title: string, html: string): string {
  return `<!doctype html><html><body style="margin:0;background:#f3f3f3;font-family:'Helvetica Neue',Arial,sans-serif;color:#0F1111">
  <div style="max-width:560px;margin:32px auto;background:#fff;border:1px solid #e7e7e7;border-radius:8px;overflow:hidden">
    <div style="background:#131A22;padding:18px 24px"><div style="color:#FF9900;font-weight:700;font-size:20px">AWZ<span style="color:#fff">.Jobs</span></div></div>
    <div style="padding:28px 24px"><h1 style="margin:0 0 12px;font-size:20px">${title}</h1>${html}</div>
    <div style="background:#f7f8fa;padding:14px 24px;border-top:1px solid #e7e7e7;font-size:12px;color:#565959;text-align:center">© AMZ.Jobs — Remote Work Opportunities</div>
  </div></body></html>`;
}

// ============================================================
// APPROVE APPLICATION + CREATE EMPLOYMENT PACKAGE
// ============================================================
export const approveApplicationWithPackage = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input) =>
    z.object({
      application_id: z.string().uuid(),
      monthly_salary: z.number().min(0).max(10_000_000),
      currency: z.string().min(3).max(8).default("INR"),
      perks: z.string().max(2000).optional().nullable(),
      starts_on: z.string().min(1).max(20),
      admin_notes: z.string().max(2000).optional().nullable(),
    }).parse(input),
  )
  .handler(async ({ data, context }) => {
    await assertAdmin(context.userId);

    const { data: app, error: aErr } = await supabaseAdmin
      .from("job_applications")
      .select("id, user_id, job_id, status")
      .eq("id", data.application_id)
      .maybeSingle();
    if (aErr) throw new Error(aErr.message);
    if (!app) throw new Error("Application not found");

    // 1. mark the application approved (idempotent)
    const { error: updErr } = await supabaseAdmin
      .from("job_applications")
      .update({ status: "approved", admin_notes: data.admin_notes ?? null })
      .eq("id", app.id);
    if (updErr) throw new Error(updErr.message);

    // 2. create active package (deactivate any prior package for that user/job)
    await supabaseAdmin
      .from("employment_packages")
      .update({ is_active: false, ends_on: data.starts_on })
      .eq("user_id", app.user_id)
      .eq("is_active", true);

    const { data: pkg, error: pkgErr } = await supabaseAdmin
      .from("employment_packages")
      .insert({
        user_id: app.user_id,
        job_id: app.job_id,
        application_id: app.id,
        monthly_salary: data.monthly_salary,
        currency: data.currency,
        perks: data.perks ? { description: data.perks } : {},
        starts_on: data.starts_on,
        is_active: true,
        notes: data.admin_notes ?? null,
        created_by: context.userId,
      })
      .select("id")
      .single();
    if (pkgErr) throw new Error(pkgErr.message);

    // 3. notification email (best-effort)
    try {
      const { data: profile } = await supabaseAdmin
        .from("profiles").select("email, full_name").eq("id", app.user_id).maybeSingle();
      const { data: job } = await supabaseAdmin
        .from("jobs").select("title").eq("id", app.job_id).maybeSingle();
      if (profile?.email) {
        const body = `
          <p>Hi ${profile.full_name || "there"},</p>
          <p>Congratulations! Your application for <strong>${job?.title || "the role"}</strong> has been approved.</p>
          <p><strong>Monthly salary:</strong> ${data.currency} ${data.monthly_salary.toLocaleString("en-IN")}<br/>
          <strong>Start date:</strong> ${data.starts_on}</p>
          ${data.perks ? `<p><strong>Perks &amp; allowances:</strong><br/>${data.perks.replace(/\n/g, "<br/>")}</p>` : ""}
          <p><a href="${siteUrl()}/dashboard" style="color:#FF9900;font-weight:bold">Open your dashboard →</a></p>
        `;
        await sendEmailViaResend({
          to: profile.email,
          toName: profile.full_name || undefined,
          subject: `You're hired — ${job?.title || "Role"} (₹${data.monthly_salary.toLocaleString("en-IN")}/mo)`,
          html: emailShell("Welcome to the team!", body),
        });
      }
    } catch (e) {
      console.error("approveApplicationWithPackage email failed:", e);
    }

    return { ok: true, package_id: pkg.id };
  });

// ============================================================
// FIRE / TERMINATE EMPLOYEE PACKAGE
// ============================================================
export const terminateEmployment = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input) =>
    z.object({
      package_id: z.string().uuid(),
      reason: z.string().min(3).max(2000),
      effective_date: z.string().min(1).max(20),
    }).parse(input),
  )
  .handler(async ({ data, context }) => {
    await assertAdmin(context.userId);
    const { data: pkg, error } = await supabaseAdmin
      .from("employment_packages")
      .update({ is_active: false, ends_on: data.effective_date, notes: data.reason })
      .eq("id", data.package_id)
      .select("user_id")
      .single();
    if (error) throw new Error(error.message);

    try {
      const { data: profile } = await supabaseAdmin
        .from("profiles").select("email, full_name").eq("id", pkg.user_id).maybeSingle();
      if (profile?.email) {
        await sendEmailViaResend({
          to: profile.email,
          toName: profile.full_name || undefined,
          subject: "Employment terminated",
          html: emailShell(
            "Your employment has ended",
            `<p>Hi ${profile.full_name || "there"},</p>
             <p>Your engagement has been ended effective <strong>${data.effective_date}</strong>.</p>
             <p><strong>Reason:</strong> ${data.reason.replace(/</g, "&lt;").replace(/\n/g, "<br/>")}</p>
             <p>Any salary accrued up to this date will still be processed in the next disbursement cycle.</p>`,
          ),
        });
      }
    } catch (e) {
      console.error("terminateEmployment email failed:", e);
    }

    return { ok: true };
  });

// ============================================================
// ADMIN: APPROVE / MARK PAID a salary disbursement
// ============================================================
export const setDisbursementStatus = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input) =>
    z.object({
      id: z.string().uuid(),
      status: z.enum(["pending", "held", "paid", "cancelled"]),
      hold_reason: z.string().max(500).optional().nullable(),
    }).parse(input),
  )
  .handler(async ({ data, context }) => {
    await assertAdmin(context.userId);
    const patch: Partial<{ status: typeof data.status; paid_at: string; hold_reason: string }> = {
      status: data.status,
    };
    if (data.status === "paid") patch.paid_at = new Date().toISOString();
    if (data.status === "held") patch.hold_reason = data.hold_reason ?? "Held by admin";
    const { error } = await supabaseAdmin
      .from("salary_disbursements")
      .update(patch)
      .eq("id", data.id);
    if (error) throw new Error(error.message);
    return { ok: true };
  });
