/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuspendedRouteImport } from './routes/suspended'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as DashboardWithdrawalsRouteImport } from './routes/dashboard.withdrawals'
import { Route as DashboardTicketsRouteImport } from './routes/dashboard.tickets'
import { Route as DashboardTasksRouteImport } from './routes/dashboard.tasks'
import { Route as DashboardSalarySlipsRouteImport } from './routes/dashboard.salary-slips'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard.projects'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardKycRouteImport } from './routes/dashboard.kyc'
import { Route as DashboardEarningsRouteImport } from './routes/dashboard.earnings'
import { Route as DashboardDataEntryRouteImport } from './routes/dashboard.data-entry'
import { Route as DashboardAttendanceRouteImport } from './routes/dashboard.attendance'
import { Route as DashboardApplicationsRouteImport } from './routes/dashboard.applications'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin.withdrawals'
import { Route as AdminTicketsRouteImport } from './routes/admin.tickets'
import { Route as AdminTasksRouteImport } from './routes/admin.tasks'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminSalarySlipsRouteImport } from './routes/admin.salary-slips'
import { Route as AdminSalaryDisbursementsRouteImport } from './routes/admin.salary-disbursements'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminReviewRouteImport } from './routes/admin.review'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminKycRouteImport } from './routes/admin.kyc'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminEmployeesRouteImport } from './routes/admin.employees'
import { Route as AdminEmailTemplatesRouteImport } from './routes/admin.email-templates'
import { Route as AdminDataEntrySubscriptionsRouteImport } from './routes/admin.data-entry-subscriptions'
import { Route as AdminDataEntryPackagesRouteImport } from './routes/admin.data-entry-packages'
import { Route as AdminDataEntryAnalyticsRouteImport } from './routes/admin.data-entry-analytics'
import { Route as AdminDataEntryRouteImport } from './routes/admin.data-entry'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as DashboardDataEntryIndexRouteImport } from './routes/dashboard.data-entry.index'
import { Route as AdminEmployeesIndexRouteImport } from './routes/admin.employees.index'
import { Route as DashboardTasksTaskIdRouteImport } from './routes/dashboard.tasks.$taskId'
import { Route as DashboardProjectsProjectIdRouteImport } from './routes/dashboard.projects.$projectId'
import { Route as DashboardKycPayRouteImport } from './routes/dashboard.kyc.pay'
import { Route as DashboardDataEntryReferralRouteImport } from './routes/dashboard.data-entry.referral'
import { Route as DashboardDataEntryPackagesRouteImport } from './routes/dashboard.data-entry.packages'
import { Route as DashboardDataEntryMyPlanRouteImport } from './routes/dashboard.data-entry.my-plan'
import { Route as AdminProjectsProjectIdRouteImport } from './routes/admin.projects.$projectId'
import { Route as AdminEmployeesUserIdRouteImport } from './routes/admin.employees.$userId'
import { Route as ApiPublicHooksTaskRemindersRouteImport } from './routes/api.public.hooks.task-reminders'
import { Route as ApiPublicHooksGenerateSalaryRouteImport } from './routes/api.public.hooks.generate-salary'
import { Route as ApiPublicHooksDailyRolloverRouteImport } from './routes/api/public/hooks/daily-rollover'

const SuspendedRoute = SuspendedRouteImport.update({
  id: '/suspended',
  path: '/suspended',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWithdrawalsRoute = DashboardWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTicketsRoute = DashboardTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSalarySlipsRoute = DashboardSalarySlipsRouteImport.update({
  id: '/salary-slips',
  path: '/salary-slips',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKycRoute = DashboardKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEarningsRoute = DashboardEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDataEntryRoute = DashboardDataEntryRouteImport.update({
  id: '/data-entry',
  path: '/data-entry',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAttendanceRoute = DashboardAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApplicationsRoute = DashboardApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksRoute = AdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalarySlipsRoute = AdminSalarySlipsRouteImport.update({
  id: '/salary-slips',
  path: '/salary-slips',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalaryDisbursementsRoute =
  AdminSalaryDisbursementsRouteImport.update({
    id: '/salary-disbursements',
    path: '/salary-disbursements',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewRoute = AdminReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailTemplatesRoute = AdminEmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataEntrySubscriptionsRoute =
  AdminDataEntrySubscriptionsRouteImport.update({
    id: '/data-entry-subscriptions',
    path: '/data-entry-subscriptions',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminDataEntryPackagesRoute = AdminDataEntryPackagesRouteImport.update({
  id: '/data-entry-packages',
  path: '/data-entry-packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataEntryAnalyticsRoute = AdminDataEntryAnalyticsRouteImport.update({
  id: '/data-entry-analytics',
  path: '/data-entry-analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataEntryRoute = AdminDataEntryRouteImport.update({
  id: '/data-entry',
  path: '/data-entry',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardDataEntryIndexRoute = DashboardDataEntryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDataEntryRoute,
} as any)
const AdminEmployeesIndexRoute = AdminEmployeesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminEmployeesRoute,
} as any)
const DashboardTasksTaskIdRoute = DashboardTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => DashboardTasksRoute,
} as any)
const DashboardProjectsProjectIdRoute =
  DashboardProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => DashboardProjectsRoute,
  } as any)
const DashboardKycPayRoute = DashboardKycPayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => DashboardKycRoute,
} as any)
const DashboardDataEntryReferralRoute =
  DashboardDataEntryReferralRouteImport.update({
    id: '/referral',
    path: '/referral',
    getParentRoute: () => DashboardDataEntryRoute,
  } as any)
const DashboardDataEntryPackagesRoute =
  DashboardDataEntryPackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => DashboardDataEntryRoute,
  } as any)
const DashboardDataEntryMyPlanRoute =
  DashboardDataEntryMyPlanRouteImport.update({
    id: '/my-plan',
    path: '/my-plan',
    getParentRoute: () => DashboardDataEntryRoute,
  } as any)
const AdminProjectsProjectIdRoute = AdminProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AdminProjectsRoute,
} as any)
const AdminEmployeesUserIdRoute = AdminEmployeesUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminEmployeesRoute,
} as any)
const ApiPublicHooksTaskRemindersRoute =
  ApiPublicHooksTaskRemindersRouteImport.update({
    id: '/api/public/hooks/task-reminders',
    path: '/api/public/hooks/task-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGenerateSalaryRoute =
  ApiPublicHooksGenerateSalaryRouteImport.update({
    id: '/api/public/hooks/generate-salary',
    path: '/api/public/hooks/generate-salary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyRolloverRoute =
  ApiPublicHooksDailyRolloverRouteImport.update({
    id: '/api/public/hooks/daily-rollover',
    path: '/api/public/hooks/daily-rollover',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/suspended': typeof SuspendedRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/data-entry': typeof AdminDataEntryRoute
  '/admin/data-entry-analytics': typeof AdminDataEntryAnalyticsRoute
  '/admin/data-entry-packages': typeof AdminDataEntryPackagesRoute
  '/admin/data-entry-subscriptions': typeof AdminDataEntrySubscriptionsRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/employees': typeof AdminEmployeesRouteWithChildren
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/projects': typeof AdminProjectsRouteWithChildren
  '/admin/review': typeof AdminReviewRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/salary-disbursements': typeof AdminSalaryDisbursementsRoute
  '/admin/salary-slips': typeof AdminSalarySlipsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/data-entry': typeof DashboardDataEntryRouteWithChildren
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/kyc': typeof DashboardKycRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/dashboard/salary-slips': typeof DashboardSalarySlipsRoute
  '/dashboard/tasks': typeof DashboardTasksRouteWithChildren
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard/withdrawals': typeof DashboardWithdrawalsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/admin/employees/$userId': typeof AdminEmployeesUserIdRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRoute
  '/dashboard/data-entry/my-plan': typeof DashboardDataEntryMyPlanRoute
  '/dashboard/data-entry/packages': typeof DashboardDataEntryPackagesRoute
  '/dashboard/data-entry/referral': typeof DashboardDataEntryReferralRoute
  '/dashboard/kyc/pay': typeof DashboardKycPayRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/tasks/$taskId': typeof DashboardTasksTaskIdRoute
  '/admin/employees/': typeof AdminEmployeesIndexRoute
  '/dashboard/data-entry/': typeof DashboardDataEntryIndexRoute
  '/api/public/hooks/daily-rollover': typeof ApiPublicHooksDailyRolloverRoute
  '/api/public/hooks/generate-salary': typeof ApiPublicHooksGenerateSalaryRoute
  '/api/public/hooks/task-reminders': typeof ApiPublicHooksTaskRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/suspended': typeof SuspendedRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/data-entry': typeof AdminDataEntryRoute
  '/admin/data-entry-analytics': typeof AdminDataEntryAnalyticsRoute
  '/admin/data-entry-packages': typeof AdminDataEntryPackagesRoute
  '/admin/data-entry-subscriptions': typeof AdminDataEntrySubscriptionsRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/projects': typeof AdminProjectsRouteWithChildren
  '/admin/review': typeof AdminReviewRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/salary-disbursements': typeof AdminSalaryDisbursementsRoute
  '/admin/salary-slips': typeof AdminSalarySlipsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/kyc': typeof DashboardKycRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/dashboard/salary-slips': typeof DashboardSalarySlipsRoute
  '/dashboard/tasks': typeof DashboardTasksRouteWithChildren
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard/withdrawals': typeof DashboardWithdrawalsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/admin/employees/$userId': typeof AdminEmployeesUserIdRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRoute
  '/dashboard/data-entry/my-plan': typeof DashboardDataEntryMyPlanRoute
  '/dashboard/data-entry/packages': typeof DashboardDataEntryPackagesRoute
  '/dashboard/data-entry/referral': typeof DashboardDataEntryReferralRoute
  '/dashboard/kyc/pay': typeof DashboardKycPayRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/tasks/$taskId': typeof DashboardTasksTaskIdRoute
  '/admin/employees': typeof AdminEmployeesIndexRoute
  '/dashboard/data-entry': typeof DashboardDataEntryIndexRoute
  '/api/public/hooks/daily-rollover': typeof ApiPublicHooksDailyRolloverRoute
  '/api/public/hooks/generate-salary': typeof ApiPublicHooksGenerateSalaryRoute
  '/api/public/hooks/task-reminders': typeof ApiPublicHooksTaskRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/suspended': typeof SuspendedRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/data-entry': typeof AdminDataEntryRoute
  '/admin/data-entry-analytics': typeof AdminDataEntryAnalyticsRoute
  '/admin/data-entry-packages': typeof AdminDataEntryPackagesRoute
  '/admin/data-entry-subscriptions': typeof AdminDataEntrySubscriptionsRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/employees': typeof AdminEmployeesRouteWithChildren
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/projects': typeof AdminProjectsRouteWithChildren
  '/admin/review': typeof AdminReviewRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/salary-disbursements': typeof AdminSalaryDisbursementsRoute
  '/admin/salary-slips': typeof AdminSalarySlipsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/data-entry': typeof DashboardDataEntryRouteWithChildren
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/kyc': typeof DashboardKycRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/dashboard/salary-slips': typeof DashboardSalarySlipsRoute
  '/dashboard/tasks': typeof DashboardTasksRouteWithChildren
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard/withdrawals': typeof DashboardWithdrawalsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/admin/employees/$userId': typeof AdminEmployeesUserIdRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRoute
  '/dashboard/data-entry/my-plan': typeof DashboardDataEntryMyPlanRoute
  '/dashboard/data-entry/packages': typeof DashboardDataEntryPackagesRoute
  '/dashboard/data-entry/referral': typeof DashboardDataEntryReferralRoute
  '/dashboard/kyc/pay': typeof DashboardKycPayRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/tasks/$taskId': typeof DashboardTasksTaskIdRoute
  '/admin/employees/': typeof AdminEmployeesIndexRoute
  '/dashboard/data-entry/': typeof DashboardDataEntryIndexRoute
  '/api/public/hooks/daily-rollover': typeof ApiPublicHooksDailyRolloverRoute
  '/api/public/hooks/generate-salary': typeof ApiPublicHooksGenerateSalaryRoute
  '/api/public/hooks/task-reminders': typeof ApiPublicHooksTaskRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/suspended'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/attendance'
    | '/admin/audit-logs'
    | '/admin/data-entry'
    | '/admin/data-entry-analytics'
    | '/admin/data-entry-packages'
    | '/admin/data-entry-subscriptions'
    | '/admin/email-templates'
    | '/admin/employees'
    | '/admin/jobs'
    | '/admin/kyc'
    | '/admin/projects'
    | '/admin/review'
    | '/admin/roles'
    | '/admin/salary-disbursements'
    | '/admin/salary-slips'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/tasks'
    | '/admin/tickets'
    | '/admin/withdrawals'
    | '/dashboard/applications'
    | '/dashboard/attendance'
    | '/dashboard/data-entry'
    | '/dashboard/earnings'
    | '/dashboard/kyc'
    | '/dashboard/profile'
    | '/dashboard/projects'
    | '/dashboard/salary-slips'
    | '/dashboard/tasks'
    | '/dashboard/tickets'
    | '/dashboard/withdrawals'
    | '/jobs/$jobId'
    | '/admin/'
    | '/dashboard/'
    | '/jobs/'
    | '/admin/employees/$userId'
    | '/admin/projects/$projectId'
    | '/dashboard/data-entry/my-plan'
    | '/dashboard/data-entry/packages'
    | '/dashboard/data-entry/referral'
    | '/dashboard/kyc/pay'
    | '/dashboard/projects/$projectId'
    | '/dashboard/tasks/$taskId'
    | '/admin/employees/'
    | '/dashboard/data-entry/'
    | '/api/public/hooks/daily-rollover'
    | '/api/public/hooks/generate-salary'
    | '/api/public/hooks/task-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/suspended'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/attendance'
    | '/admin/audit-logs'
    | '/admin/data-entry'
    | '/admin/data-entry-analytics'
    | '/admin/data-entry-packages'
    | '/admin/data-entry-subscriptions'
    | '/admin/email-templates'
    | '/admin/jobs'
    | '/admin/kyc'
    | '/admin/projects'
    | '/admin/review'
    | '/admin/roles'
    | '/admin/salary-disbursements'
    | '/admin/salary-slips'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/tasks'
    | '/admin/tickets'
    | '/admin/withdrawals'
    | '/dashboard/applications'
    | '/dashboard/attendance'
    | '/dashboard/earnings'
    | '/dashboard/kyc'
    | '/dashboard/profile'
    | '/dashboard/projects'
    | '/dashboard/salary-slips'
    | '/dashboard/tasks'
    | '/dashboard/tickets'
    | '/dashboard/withdrawals'
    | '/jobs/$jobId'
    | '/admin'
    | '/dashboard'
    | '/jobs'
    | '/admin/employees/$userId'
    | '/admin/projects/$projectId'
    | '/dashboard/data-entry/my-plan'
    | '/dashboard/data-entry/packages'
    | '/dashboard/data-entry/referral'
    | '/dashboard/kyc/pay'
    | '/dashboard/projects/$projectId'
    | '/dashboard/tasks/$taskId'
    | '/admin/employees'
    | '/dashboard/data-entry'
    | '/api/public/hooks/daily-rollover'
    | '/api/public/hooks/generate-salary'
    | '/api/public/hooks/task-reminders'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/suspended'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/attendance'
    | '/admin/audit-logs'
    | '/admin/data-entry'
    | '/admin/data-entry-analytics'
    | '/admin/data-entry-packages'
    | '/admin/data-entry-subscriptions'
    | '/admin/email-templates'
    | '/admin/employees'
    | '/admin/jobs'
    | '/admin/kyc'
    | '/admin/projects'
    | '/admin/review'
    | '/admin/roles'
    | '/admin/salary-disbursements'
    | '/admin/salary-slips'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/tasks'
    | '/admin/tickets'
    | '/admin/withdrawals'
    | '/dashboard/applications'
    | '/dashboard/attendance'
    | '/dashboard/data-entry'
    | '/dashboard/earnings'
    | '/dashboard/kyc'
    | '/dashboard/profile'
    | '/dashboard/projects'
    | '/dashboard/salary-slips'
    | '/dashboard/tasks'
    | '/dashboard/tickets'
    | '/dashboard/withdrawals'
    | '/jobs/$jobId'
    | '/admin/'
    | '/dashboard/'
    | '/jobs/'
    | '/admin/employees/$userId'
    | '/admin/projects/$projectId'
    | '/dashboard/data-entry/my-plan'
    | '/dashboard/data-entry/packages'
    | '/dashboard/data-entry/referral'
    | '/dashboard/kyc/pay'
    | '/dashboard/projects/$projectId'
    | '/dashboard/tasks/$taskId'
    | '/admin/employees/'
    | '/dashboard/data-entry/'
    | '/api/public/hooks/daily-rollover'
    | '/api/public/hooks/generate-salary'
    | '/api/public/hooks/task-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SuspendedRoute: typeof SuspendedRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
  ApiPublicHooksDailyRolloverRoute: typeof ApiPublicHooksDailyRolloverRoute
  ApiPublicHooksGenerateSalaryRoute: typeof ApiPublicHooksGenerateSalaryRoute
  ApiPublicHooksTaskRemindersRoute: typeof ApiPublicHooksTaskRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suspended': {
      id: '/suspended'
      path: '/suspended'
      fullPath: '/suspended'
      preLoaderRoute: typeof SuspendedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/withdrawals': {
      id: '/dashboard/withdrawals'
      path: '/withdrawals'
      fullPath: '/dashboard/withdrawals'
      preLoaderRoute: typeof DashboardWithdrawalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tickets': {
      id: '/dashboard/tickets'
      path: '/tickets'
      fullPath: '/dashboard/tickets'
      preLoaderRoute: typeof DashboardTicketsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tasks': {
      id: '/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/salary-slips': {
      id: '/dashboard/salary-slips'
      path: '/salary-slips'
      fullPath: '/dashboard/salary-slips'
      preLoaderRoute: typeof DashboardSalarySlipsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/kyc': {
      id: '/dashboard/kyc'
      path: '/kyc'
      fullPath: '/dashboard/kyc'
      preLoaderRoute: typeof DashboardKycRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/earnings': {
      id: '/dashboard/earnings'
      path: '/earnings'
      fullPath: '/dashboard/earnings'
      preLoaderRoute: typeof DashboardEarningsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/data-entry': {
      id: '/dashboard/data-entry'
      path: '/data-entry'
      fullPath: '/dashboard/data-entry'
      preLoaderRoute: typeof DashboardDataEntryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/attendance': {
      id: '/dashboard/attendance'
      path: '/attendance'
      fullPath: '/dashboard/attendance'
      preLoaderRoute: typeof DashboardAttendanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/applications': {
      id: '/dashboard/applications'
      path: '/applications'
      fullPath: '/dashboard/applications'
      preLoaderRoute: typeof DashboardApplicationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tasks': {
      id: '/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/salary-slips': {
      id: '/admin/salary-slips'
      path: '/salary-slips'
      fullPath: '/admin/salary-slips'
      preLoaderRoute: typeof AdminSalarySlipsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/salary-disbursements': {
      id: '/admin/salary-disbursements'
      path: '/salary-disbursements'
      fullPath: '/admin/salary-disbursements'
      preLoaderRoute: typeof AdminSalaryDisbursementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/review': {
      id: '/admin/review'
      path: '/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AdminReviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/email-templates': {
      id: '/admin/email-templates'
      path: '/email-templates'
      fullPath: '/admin/email-templates'
      preLoaderRoute: typeof AdminEmailTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data-entry-subscriptions': {
      id: '/admin/data-entry-subscriptions'
      path: '/data-entry-subscriptions'
      fullPath: '/admin/data-entry-subscriptions'
      preLoaderRoute: typeof AdminDataEntrySubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data-entry-packages': {
      id: '/admin/data-entry-packages'
      path: '/data-entry-packages'
      fullPath: '/admin/data-entry-packages'
      preLoaderRoute: typeof AdminDataEntryPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data-entry-analytics': {
      id: '/admin/data-entry-analytics'
      path: '/data-entry-analytics'
      fullPath: '/admin/data-entry-analytics'
      preLoaderRoute: typeof AdminDataEntryAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data-entry': {
      id: '/admin/data-entry'
      path: '/data-entry'
      fullPath: '/admin/data-entry'
      preLoaderRoute: typeof AdminDataEntryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/data-entry/': {
      id: '/dashboard/data-entry/'
      path: '/'
      fullPath: '/dashboard/data-entry/'
      preLoaderRoute: typeof DashboardDataEntryIndexRouteImport
      parentRoute: typeof DashboardDataEntryRoute
    }
    '/admin/employees/': {
      id: '/admin/employees/'
      path: '/'
      fullPath: '/admin/employees/'
      preLoaderRoute: typeof AdminEmployeesIndexRouteImport
      parentRoute: typeof AdminEmployeesRoute
    }
    '/dashboard/tasks/$taskId': {
      id: '/dashboard/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/dashboard/tasks/$taskId'
      preLoaderRoute: typeof DashboardTasksTaskIdRouteImport
      parentRoute: typeof DashboardTasksRoute
    }
    '/dashboard/projects/$projectId': {
      id: '/dashboard/projects/$projectId'
      path: '/$projectId'
      fullPath: '/dashboard/projects/$projectId'
      preLoaderRoute: typeof DashboardProjectsProjectIdRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/dashboard/kyc/pay': {
      id: '/dashboard/kyc/pay'
      path: '/pay'
      fullPath: '/dashboard/kyc/pay'
      preLoaderRoute: typeof DashboardKycPayRouteImport
      parentRoute: typeof DashboardKycRoute
    }
    '/dashboard/data-entry/referral': {
      id: '/dashboard/data-entry/referral'
      path: '/referral'
      fullPath: '/dashboard/data-entry/referral'
      preLoaderRoute: typeof DashboardDataEntryReferralRouteImport
      parentRoute: typeof DashboardDataEntryRoute
    }
    '/dashboard/data-entry/packages': {
      id: '/dashboard/data-entry/packages'
      path: '/packages'
      fullPath: '/dashboard/data-entry/packages'
      preLoaderRoute: typeof DashboardDataEntryPackagesRouteImport
      parentRoute: typeof DashboardDataEntryRoute
    }
    '/dashboard/data-entry/my-plan': {
      id: '/dashboard/data-entry/my-plan'
      path: '/my-plan'
      fullPath: '/dashboard/data-entry/my-plan'
      preLoaderRoute: typeof DashboardDataEntryMyPlanRouteImport
      parentRoute: typeof DashboardDataEntryRoute
    }
    '/admin/projects/$projectId': {
      id: '/admin/projects/$projectId'
      path: '/$projectId'
      fullPath: '/admin/projects/$projectId'
      preLoaderRoute: typeof AdminProjectsProjectIdRouteImport
      parentRoute: typeof AdminProjectsRoute
    }
    '/admin/employees/$userId': {
      id: '/admin/employees/$userId'
      path: '/$userId'
      fullPath: '/admin/employees/$userId'
      preLoaderRoute: typeof AdminEmployeesUserIdRouteImport
      parentRoute: typeof AdminEmployeesRoute
    }
    '/api/public/hooks/task-reminders': {
      id: '/api/public/hooks/task-reminders'
      path: '/api/public/hooks/task-reminders'
      fullPath: '/api/public/hooks/task-reminders'
      preLoaderRoute: typeof ApiPublicHooksTaskRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-salary': {
      id: '/api/public/hooks/generate-salary'
      path: '/api/public/hooks/generate-salary'
      fullPath: '/api/public/hooks/generate-salary'
      preLoaderRoute: typeof ApiPublicHooksGenerateSalaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-rollover': {
      id: '/api/public/hooks/daily-rollover'
      path: '/api/public/hooks/daily-rollover'
      fullPath: '/api/public/hooks/daily-rollover'
      preLoaderRoute: typeof ApiPublicHooksDailyRolloverRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminEmployeesRouteChildren {
  AdminEmployeesUserIdRoute: typeof AdminEmployeesUserIdRoute
  AdminEmployeesIndexRoute: typeof AdminEmployeesIndexRoute
}

const AdminEmployeesRouteChildren: AdminEmployeesRouteChildren = {
  AdminEmployeesUserIdRoute: AdminEmployeesUserIdRoute,
  AdminEmployeesIndexRoute: AdminEmployeesIndexRoute,
}

const AdminEmployeesRouteWithChildren = AdminEmployeesRoute._addFileChildren(
  AdminEmployeesRouteChildren,
)

interface AdminProjectsRouteChildren {
  AdminProjectsProjectIdRoute: typeof AdminProjectsProjectIdRoute
}

const AdminProjectsRouteChildren: AdminProjectsRouteChildren = {
  AdminProjectsProjectIdRoute: AdminProjectsProjectIdRoute,
}

const AdminProjectsRouteWithChildren = AdminProjectsRoute._addFileChildren(
  AdminProjectsRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminDataEntryRoute: typeof AdminDataEntryRoute
  AdminDataEntryAnalyticsRoute: typeof AdminDataEntryAnalyticsRoute
  AdminDataEntryPackagesRoute: typeof AdminDataEntryPackagesRoute
  AdminDataEntrySubscriptionsRoute: typeof AdminDataEntrySubscriptionsRoute
  AdminEmailTemplatesRoute: typeof AdminEmailTemplatesRoute
  AdminEmployeesRoute: typeof AdminEmployeesRouteWithChildren
  AdminJobsRoute: typeof AdminJobsRoute
  AdminKycRoute: typeof AdminKycRoute
  AdminProjectsRoute: typeof AdminProjectsRouteWithChildren
  AdminReviewRoute: typeof AdminReviewRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSalaryDisbursementsRoute: typeof AdminSalaryDisbursementsRoute
  AdminSalarySlipsRoute: typeof AdminSalarySlipsRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTasksRoute: typeof AdminTasksRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminDataEntryRoute: AdminDataEntryRoute,
  AdminDataEntryAnalyticsRoute: AdminDataEntryAnalyticsRoute,
  AdminDataEntryPackagesRoute: AdminDataEntryPackagesRoute,
  AdminDataEntrySubscriptionsRoute: AdminDataEntrySubscriptionsRoute,
  AdminEmailTemplatesRoute: AdminEmailTemplatesRoute,
  AdminEmployeesRoute: AdminEmployeesRouteWithChildren,
  AdminJobsRoute: AdminJobsRoute,
  AdminKycRoute: AdminKycRoute,
  AdminProjectsRoute: AdminProjectsRouteWithChildren,
  AdminReviewRoute: AdminReviewRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSalaryDisbursementsRoute: AdminSalaryDisbursementsRoute,
  AdminSalarySlipsRoute: AdminSalarySlipsRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTasksRoute: AdminTasksRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardDataEntryRouteChildren {
  DashboardDataEntryMyPlanRoute: typeof DashboardDataEntryMyPlanRoute
  DashboardDataEntryPackagesRoute: typeof DashboardDataEntryPackagesRoute
  DashboardDataEntryReferralRoute: typeof DashboardDataEntryReferralRoute
  DashboardDataEntryIndexRoute: typeof DashboardDataEntryIndexRoute
}

const DashboardDataEntryRouteChildren: DashboardDataEntryRouteChildren = {
  DashboardDataEntryMyPlanRoute: DashboardDataEntryMyPlanRoute,
  DashboardDataEntryPackagesRoute: DashboardDataEntryPackagesRoute,
  DashboardDataEntryReferralRoute: DashboardDataEntryReferralRoute,
  DashboardDataEntryIndexRoute: DashboardDataEntryIndexRoute,
}

const DashboardDataEntryRouteWithChildren =
  DashboardDataEntryRoute._addFileChildren(DashboardDataEntryRouteChildren)

interface DashboardKycRouteChildren {
  DashboardKycPayRoute: typeof DashboardKycPayRoute
}

const DashboardKycRouteChildren: DashboardKycRouteChildren = {
  DashboardKycPayRoute: DashboardKycPayRoute,
}

const DashboardKycRouteWithChildren = DashboardKycRoute._addFileChildren(
  DashboardKycRouteChildren,
)

interface DashboardProjectsRouteChildren {
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRoute
}

const DashboardProjectsRouteChildren: DashboardProjectsRouteChildren = {
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRoute,
}

const DashboardProjectsRouteWithChildren =
  DashboardProjectsRoute._addFileChildren(DashboardProjectsRouteChildren)

interface DashboardTasksRouteChildren {
  DashboardTasksTaskIdRoute: typeof DashboardTasksTaskIdRoute
}

const DashboardTasksRouteChildren: DashboardTasksRouteChildren = {
  DashboardTasksTaskIdRoute: DashboardTasksTaskIdRoute,
}

const DashboardTasksRouteWithChildren = DashboardTasksRoute._addFileChildren(
  DashboardTasksRouteChildren,
)

interface DashboardRouteChildren {
  DashboardApplicationsRoute: typeof DashboardApplicationsRoute
  DashboardAttendanceRoute: typeof DashboardAttendanceRoute
  DashboardDataEntryRoute: typeof DashboardDataEntryRouteWithChildren
  DashboardEarningsRoute: typeof DashboardEarningsRoute
  DashboardKycRoute: typeof DashboardKycRouteWithChildren
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardProjectsRoute: typeof DashboardProjectsRouteWithChildren
  DashboardSalarySlipsRoute: typeof DashboardSalarySlipsRoute
  DashboardTasksRoute: typeof DashboardTasksRouteWithChildren
  DashboardTicketsRoute: typeof DashboardTicketsRoute
  DashboardWithdrawalsRoute: typeof DashboardWithdrawalsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardApplicationsRoute: DashboardApplicationsRoute,
  DashboardAttendanceRoute: DashboardAttendanceRoute,
  DashboardDataEntryRoute: DashboardDataEntryRouteWithChildren,
  DashboardEarningsRoute: DashboardEarningsRoute,
  DashboardKycRoute: DashboardKycRouteWithChildren,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardProjectsRoute: DashboardProjectsRouteWithChildren,
  DashboardSalarySlipsRoute: DashboardSalarySlipsRoute,
  DashboardTasksRoute: DashboardTasksRouteWithChildren,
  DashboardTicketsRoute: DashboardTicketsRoute,
  DashboardWithdrawalsRoute: DashboardWithdrawalsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SuspendedRoute: SuspendedRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  JobsIndexRoute: JobsIndexRoute,
  ApiPublicHooksDailyRolloverRoute: ApiPublicHooksDailyRolloverRoute,
  ApiPublicHooksGenerateSalaryRoute: ApiPublicHooksGenerateSalaryRoute,
  ApiPublicHooksTaskRemindersRoute: ApiPublicHooksTaskRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
